/* AUTOGENERATED. DO NOT MODIFY */

#ifndef __AUTO_MCS_H
#define __AUTO_MCS_H

#ifndef __MCS_H
#error "This header should not be included directly. Include mcs.h"
#endif

typedef enum MCSCommand {
    MCS_MESSAGE_PROCMAN_START     = 0
    MCS_STATE_TEMPERATURE_ARDUINO = 65536 , /* 0 x10000 */
    MCS_PAYLOAD_ARDUINO_GET_PIN   = 131072 , /* 0 x20000 */
} MCSCommand;

const static struct MCSCommandOptionsMessage mcs_command_message_list[] =
{
    {
    .cmd = {
        .name = "procman_start",
        /*Start the Process Manager*/
        .nargs = 0,
        .raw_data = false,
        .response_size = 0,
    },
    .destination = "procman",
    .origin_groups = {syscore},
    .destination_groups = NULL,
    }
};

#define mcs_command_message_list_size 1

const static struct MCSCommandOptionsState mcs_command_state_list[] =
{
    {
    .cmd = {
        .name = "temperature_arduino",
        /*Get temperature from the embedded sensor in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 8,
    },
    .request = get_sensor_value_arduino (1),
    .dimensions = 1,
    /*Unit: K/
    /*Dimension_name: NULL*/
    .expire_group = {
            { .group = app, .max_espire = 15 },
    },
};

#define mcs_command_state_list_size 1

const static struct MCSCommandOptionsPayload mcs_command_payload_list[] =
{
    {
    .cmd = {
        .name = "arduino_get_pin",
        /*Get the value of the given pin in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 1,
    },
    .command = "001",
    .parameters = "0110",
    .arguments = "@arg0",
    .data = NULL,
    },
};

#define mcs_command_payload_list_size 1

#endif