/* AUTOGENERATED. DO NOT MODIFY */

#ifndef __AUTO_MCS_H
#define __AUTO_MCS_H

#ifndef __MCS_H
#error "This header should not be included directly. Include mcs.h"
#endif

typedef enum MCSCommand {
    MCS_SPAYLOAD_ARDUINO_GET_PIN = 131074,
    MCS_STATE_TEMPERATURE_ARDUINO1 = 65537,
    MCS_MESSAGE_PROCMAN_1 = 0,
} MCSCommand;

static const struct MCSCommandOptionsMessage mcs_command_message_list[] =
{
    {
    .cmd = {
        .name = "procman_1",
        /*Start the Process Manager*/
        .nargs = 0,
        .raw_data = false,
        .response_size = 0,
    },
    .destination = "procman",
    .origin_groups = {syscore, second_group},
    .destination_groups = {destination2, destination2},
    },
};

#define mcs_command_message_list_size 1

static const struct MCSCommandOptionsState mcs_command_state_list[] =
{
    {
    .cmd = {
        .name = "temperature_arduino1",
        /*Get temperature from the embedded sensor in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 8,
    },
    .request = get_sensor_value_arduino (1),
    .dimensions = 1,
    /*Unit: K/
    /*Dimension_name: NULL*/
    .expire_group = {
            { .group = app, .max_espire = 15 },
        },
    },
};

#define mcs_command_state_list_size 1

static const struct MCSCommandOptionsPayload mcs_command_payload_list[] =
{
    {
    .cmd = {
        .name = "arduino_get_pin",
        /*Get the value of the given pin in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 1,
    },
    .command = 1,
    .parameters = 6,
    .arguments = "@0",
    .data = NULL,
    },
};

#define mcs_command_payload_list_size 1

#endif