/* AUTOGENERATED. DO NOT MODIFY */

#ifndef __AUTO_MCS_H
#define __AUTO_MCS_H

#ifndef __MCS_H
#error "This header should not be included directly. Include mcs.h"
#endif

typedef enum MCSCommand {
    MCS_MESSAGE_PROCMAN_3 = 0,
    MCS_MESSAGE_PROCMAN_2 = 1,
    MCS_MESSAGE_PROCMAN_1 = 2,
    MCS_STATE_TEMPERATURE_ARDUINO3 = 65539,
    MCS_STATE_TEMPERATURE_ARDUINO2 = 65540,
    MCS_STATE_TEMPERATURE_ARDUINO1 = 65541,
    MCS_PAYLOAD_ARDUINO_GET_PIN3 = 131078,
    MCS_PAYLOAD_ARDUINO_GET_PIN2 = 131079,
    MCS_PAYLOAD_ARDUINO_GET_PIN1 = 131080,
} MCSCommand;

const static struct MCSCommandOptionsMessage mcs_command_message_list[] =
{
    {
    .cmd = {
        .name = "procman_3",
        /*Start the Process Manager*/
        .nargs = 0,
        .raw_data = false,
        .response_size = 0,
    },
    .destination = "procman",
    .origin_groups = {syscore},
    .destination_groups = NULL,
    },
    {
    .cmd = {
        .name = "procman_2",
        /*Start the Process Manager*/
        .nargs = 0,
        .raw_data = false,
        .response_size = 0,
    },
    .destination = "procman",
    .origin_groups = {syscore},
    .destination_groups = NULL,
    },
    {
    .cmd = {
        .name = "procman_1",
        /*Start the Process Manager*/
        .nargs = 0,
        .raw_data = false,
        .response_size = 0,
    },
    .destination = "procman",
    .origin_groups = {syscore},
    .destination_groups = NULL,
    },
};

#define mcs_command_message_list_size 3

const static struct MCSCommandOptionsState mcs_command_state_list[] =
{
    {
    .cmd = {
        .name = "temperature_arduino3",
        /*Get temperature from the embedded sensor in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 8,
    },
    .request = get_sensor_value_arduino (1),
    .dimensions = 1,
    /*Unit: K/
    /*Dimension_name: NULL*/
    .expire_group = {
            { .group = app, .max_espire = 15 },
        },
    },
    {
    .cmd = {
        .name = "temperature_arduino2",
        /*Get temperature from the embedded sensor in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 8,
    },
    .request = get_sensor_value_arduino (1),
    .dimensions = 1,
    /*Unit: K/
    /*Dimension_name: NULL*/
    .expire_group = {
            { .group = app, .max_espire = 15 },
        },
    },
    {
    .cmd = {
        .name = "temperature_arduino1",
        /*Get temperature from the embedded sensor in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 8,
    },
    .request = get_sensor_value_arduino (1),
    .dimensions = 1,
    /*Unit: K/
    /*Dimension_name: NULL*/
    .expire_group = {
            { .group = app, .max_espire = 15 },
        },
    },
};

#define mcs_command_state_list_size 3

const static struct MCSCommandOptionsPayload mcs_command_payload_list[] =
{
    {
    .cmd = {
        .name = "arduino_get_pin3",
        /*Get the value of the given pin in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 1,
    },
    .command = "001",
    .parameters = "0110",
    .arguments = "@arg0",
    .data = NULL,
    },
    {
    .cmd = {
        .name = "arduino_get_pin2",
        /*Get the value of the given pin in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 1,
    },
    .command = "001",
    .parameters = "0110",
    .arguments = "@arg0",
    .data = NULL,
    },
    {
    .cmd = {
        .name = "arduino_get_pin1",
        /*Get the value of the given pin in the Arduino board*/
        .nargs = 1,
        .raw_data = false,
        .response_size = 1,
    },
    .command = "001",
    .parameters = "0110",
    .arguments = "@arg0",
    .data = NULL,
    },
};

#define mcs_command_payload_list_size 3

#endif